language: python
python:
  - "2.7"
before_install:
 - deactivate
 - virtualenv --system-site-packages ~/virtualenv/this
 - source ~/virtualenv/this/bin/activate
 - sudo apt-get install -qq python-numpy python-scipy
install:
  - python setup.py dev
script: py.test
